-- Create tables
create table profiles (
  id uuid references auth.users not null,
  email text,
  username text,
  primary key (id)
);

create table toilets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  address text,
  lat double precision not null,
  lng double precision not null,
  is_accessible boolean default false,
  price numeric, -- null means free
  description text
);

-- Turn on Row Level Security
alter table profiles enable row level security;
alter table toilets enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Toilets are viewable by everyone." on toilets for select using ( true );
-- Only admins/service role might edit toilets, for this app we'll assume read-only for public

-- Seed Data (Test Data)
insert into toilets (name, address, lat, lng, is_accessible, price, description) values
('Bar "Le Suisse"', 'Rue du 23-Juin 15', 47.3686, 7.3456, true, null, 'Customer only, but friendly.'),
('Toilettes Publiques', 'Rue des Malvoisins 18', 47.3650, 7.3400, true, 0.00, 'Clean public toilet.'),
('Gare CFF', 'Place de la Gare', 47.3700, 7.3500, true, 1.00, 'Main station toilets.'),
('Parc du Ville', 'Avenue du Parc', 47.3600, 7.3450, false, 0.00, 'Open during day only.');
